CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE characters (id TEXT PRIMARY KEY, name TEXT NOT NULL, status TEXT NOT NULL, is_seller INTEGER NOT NULL DEFAULT 0, balance TEXT, updated_at TEXT);
CREATE UNIQUE INDEX one_seller ON characters(is_seller) WHERE is_seller=1;
CREATE TABLE deals (id TEXT PRIMARY KEY, source TEXT NOT NULL, destination TEXT NOT NULL, status TEXT NOT NULL, seller_id TEXT NOT NULL, forecast TEXT NOT NULL, created_at TEXT NOT NULL, parent_id TEXT REFERENCES deals(id), route_mode TEXT NOT NULL DEFAULT 'highsec');
CREATE TABLE deal_lines (id TEXT PRIMARY KEY, deal_id TEXT NOT NULL REFERENCES deals(id), type_id TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity>0), name TEXT NOT NULL);
CREATE TABLE budget_reservations (id TEXT PRIMARY KEY, deal_id TEXT NOT NULL REFERENCES deals(id), type_id TEXT NOT NULL, kind TEXT NOT NULL, amount TEXT NOT NULL, paid INTEGER NOT NULL DEFAULT 0);
CREATE TABLE wallet_snapshots (id TEXT PRIMARY KEY, captured_at TEXT NOT NULL, balances TEXT NOT NULL, reconciled INTEGER NOT NULL);
CREATE TABLE wallet_transactions (source TEXT NOT NULL, character_id TEXT NOT NULL, id TEXT NOT NULL, payload TEXT NOT NULL, imported_at TEXT NOT NULL, PRIMARY KEY(source,character_id,id));
CREATE TABLE wallet_journal (character_id TEXT NOT NULL, id TEXT NOT NULL, payload TEXT NOT NULL, imported_at TEXT NOT NULL, PRIMARY KEY(character_id,id));
CREATE TABLE internal_transfers (id TEXT PRIMARY KEY, payload TEXT NOT NULL, matched INTEGER NOT NULL DEFAULT 0);
CREATE TABLE purchase_lots (id TEXT PRIMARY KEY, deal_id TEXT NOT NULL REFERENCES deals(id), type_id TEXT NOT NULL, buyer_id TEXT NOT NULL, transaction_id TEXT NOT NULL, acquired_at TEXT NOT NULL, quantity INTEGER NOT NULL, remaining INTEGER NOT NULL, unit_cost TEXT NOT NULL, location_id TEXT NOT NULL, eligibility TEXT NOT NULL DEFAULT 'review', UNIQUE(buyer_id,transaction_id));
CREATE TABLE sale_allocations (id TEXT PRIMARY KEY, lot_id TEXT NOT NULL REFERENCES purchase_lots(id), seller_id TEXT NOT NULL, transaction_id TEXT NOT NULL, quantity INTEGER NOT NULL, proceeds TEXT NOT NULL, cost TEXT NOT NULL, tax TEXT, UNIQUE(lot_id,seller_id,transaction_id));
CREATE TABLE fee_allocations (id TEXT PRIMARY KEY, deal_id TEXT NOT NULL REFERENCES deals(id), journal_id TEXT NOT NULL, character_id TEXT NOT NULL, amount TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, UNIQUE(deal_id,character_id,journal_id));
CREATE TABLE deal_events (id TEXT PRIMARY KEY, deal_id TEXT NOT NULL REFERENCES deals(id), at TEXT NOT NULL, kind TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE reconciliation_runs (id TEXT PRIMARY KEY, deal_id TEXT NOT NULL REFERENCES deals(id), at TEXT NOT NULL, status TEXT NOT NULL, details TEXT NOT NULL);
CREATE TABLE sync_cursors (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE item_types (id TEXT PRIMARY KEY, name TEXT NOT NULL, english_name TEXT NOT NULL, group_id TEXT NOT NULL, market_group_id TEXT, volume TEXT, payload TEXT NOT NULL);
CREATE TABLE systems (id TEXT PRIMARY KEY, name TEXT NOT NULL, region_id TEXT NOT NULL, security REAL NOT NULL);
CREATE TABLE stargates (source TEXT NOT NULL REFERENCES systems(id), destination TEXT NOT NULL REFERENCES systems(id), PRIMARY KEY(source,destination));
CREATE TABLE stations (id TEXT PRIMARY KEY, name TEXT NOT NULL, system_id TEXT NOT NULL REFERENCES systems(id), owner_id TEXT NOT NULL, region_id TEXT NOT NULL);
CREATE TABLE market_snapshot_runs (id TEXT PRIMARY KEY, region_id TEXT NOT NULL, started_at TEXT NOT NULL, completed_at TEXT, modified_at TEXT, expires_at TEXT, status TEXT NOT NULL, pages INTEGER NOT NULL);
CREATE TABLE market_orders (generation TEXT NOT NULL REFERENCES market_snapshot_runs(id) ON DELETE CASCADE, id TEXT NOT NULL, type_id TEXT NOT NULL, location_id TEXT NOT NULL, payload TEXT NOT NULL, PRIMARY KEY(generation,id));
CREATE INDEX market_type_location ON market_orders(type_id,location_id);
CREATE TABLE regional_history (type_id TEXT NOT NULL, region_id TEXT NOT NULL, date TEXT NOT NULL, payload TEXT NOT NULL, available_at TEXT NOT NULL, PRIMARY KEY(type_id,region_id,date));
CREATE TABLE station_observations (id TEXT PRIMARY KEY, station_id TEXT NOT NULL, type_id TEXT NOT NULL, at TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE opportunities (id TEXT PRIMARY KEY, at TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE opportunity_features (id TEXT PRIMARY KEY, opportunity_id TEXT NOT NULL, event_time TEXT NOT NULL, available_at TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE settings_versions (id TEXT PRIMARY KEY, at TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE model_versions (id TEXT PRIMARY KEY, payload TEXT NOT NULL);
